server:
  port: 8443
  servlet:
    context-path: /Ideax

spring:
  application:
    name: ideax

  datasource:
    url: jdbc:mysql://localhost:3306/Ideax
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver